### ISSUE TITLE
to fix, 

### ISSUE THREAD

**Issue by christine-aqui** [christine-aqui/mongo-scraper#6]
==> 🌎  Listening on port 3000. Visit http://localhost:3000/ in your browser.
(node:39972) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
mongoose connection is good
(node:39972) DeprecationWarning: collection.find option [fields] is deprecated and will
be removed in a later version.
TypeError: Cannot read property '_id' of undefined
    at Object.update (c:\Users\chris\Desktop\Homework18\mongo-scraper\controllers\article.js:45:32)
    at c:\Users\chris\Desktop\Homework18\mongo-scraper\config\routes.js:65:23
    at Layer.handle [as handle_request] (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\layer.js:95:5)
    at c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\index.js:335:12)
    at next (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\index.js:174:3)
    at router (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\index.js:317:13)
    at c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\index.js:335:12)
    at next (c:\Users\chris\Desktop\Homework18\mongo-scraper\node_modules\express\lib\router\index.js:275:10)

**Comment by chris-aqui** [comment]
fixed.
Issue was the req.body was being parsed.

I added the following into /public/js/index.js
    $.ajax({
      method: "PUT",
      contentType: "application/json",
      dataType: "json",
      url: "/api/post/"+postToSave._id,
      data: JSON.stringify(postToSave)
      })
